<?php

declare(strict_types=1);

namespace PandaPanel\Console\Commands;

use Illuminate\Support\Str;

/**
 * Generates a resource and the classes it needs to work.
 *
 * Every flag changes the output. A flag that were accepted and ignored would
 * be worse than not having it, because it would read as supported.
 */
final class MakePanelResourceCommand extends PanelGeneratorCommand
{
    protected $signature = 'make:panel-resource
        {name : The resource name, for example User}
        {--panel= : The panel it belongs to}
        {--model= : The model class, defaults to App\\Models\\{name}}
        {--simple : Generate only a list page, for modal-based editing}
        {--no-view : Omit the view page}
        {--soft-deletes : Reach trashed records, and add the trashed filter with restore and force-delete actions}
        {--force}';

    protected $description = 'Create a panel resource with its pages, table, and form';

    public function handle(): int
    {
        $panel = $this->panelName((string) $this->option('panel'));

        if ($panel === '') {
            $this->components->error('The --panel option is required.');

            return self::FAILURE;
        }

        $class = Str::studly(Str::singular((string) $this->argument('name')));
        $plural = Str::pluralStudly($class);
        $model = (string) ($this->option('model') ?: "App\\Models\\{$class}");

        $pages = $this->pages();

        $this->writeStub('resource', $this->resourcePath($panel, $plural, "{$class}Resource.php"), [
            'panel' => $panel,
            'class' => $class,
            'plural' => $plural,
            'model' => ltrim($model, '\\'),
            'modelBasename' => class_basename($model),
            'imports' => $this->imports([
                ltrim($model, '\\'),
                'PandaPanel\\Forms\\FormSchema',
                'PandaPanel\\Resources\\Resource',
                'PandaPanel\\Tables\\TableSchema',
                "App\\Panels\\{$panel}\\Resources\\{$plural}\\Forms\\{$class}Form",
                "App\\Panels\\{$panel}\\Resources\\{$plural}\\Tables\\{$plural}Table",
                ...$this->pageClasses($panel, $plural, $pages),
            ]),
            'pageEntries' => $this->pageEntries($pages),
            'softDeletes' => $this->softDeletesDeclaration(),
        ]);

        foreach ($pages as $key => [$pageClass, $base]) {
            unset($key);

            $this->writeStub('resource-page', $this->resourcePath($panel, $plural, "Pages/{$pageClass}.php"), [
                'panel' => $panel,
                'class' => $class,
                'plural' => $plural,
                'pageClass' => $pageClass,
                'base' => $base,
            ]);
        }

        $this->writeStub('resource-table', $this->resourcePath($panel, $plural, "Tables/{$plural}Table.php"), [
            'panel' => $panel,
            'class' => $class,
            'plural' => $plural,
            'imports' => $this->imports([
                'PandaPanel\\Tables\\Columns\\DateTimeColumn',
                'PandaPanel\\Tables\\Columns\\TextColumn',
                'PandaPanel\\Tables\\Enums\\SortDirection',
                'PandaPanel\\Tables\\TableSchema',
                "App\\Panels\\{$panel}\\Resources\\{$plural}\\{$class}Resource",
                ...$this->actionClasses($pages),
            ]),
            'filters' => $this->filters(),
            'recordActions' => $this->recordActions($class, $pages),
            'bulkActions' => $this->bulkActions($class),
        ]);

        $this->writeStub('resource-form', $this->resourcePath($panel, $plural, "Forms/{$class}Form.php"), [
            'panel' => $panel,
            'class' => $class,
            'plural' => $plural,
        ]);

        return $this->report();
    }

    /**
     * Page key to [class suffix, base class].
     *
     * `--simple` keeps only the list page; `--no-view` drops the view page.
     * The view page is generated by default, which is why there is no
     * `--view` flag: it would have nothing to do.
     *
     * @return array<string, array{0: string, 1: string}>
     */
    private function pages(): array
    {
        $class = Str::studly(Str::singular((string) $this->argument('name')));
        $plural = Str::pluralStudly($class);

        if ($this->option('simple')) {
            return ['index' => ["List{$plural}", 'ListRecords']];
        }

        $pages = [
            'index' => ["List{$plural}", 'ListRecords'],
            'create' => ["Create{$class}", 'CreateRecord'],
            'view' => ["View{$class}", 'ViewRecord'],
            'edit' => ["Edit{$class}", 'EditRecord'],
        ];

        if ($this->option('no-view')) {
            unset($pages['view']);
        }

        return $pages;
    }

    /**
     * Generated code has to pass the project's own Pint run, and Pint sorts
     * imports. Building the block here rather than interleaving fixed and
     * generated lines in the stub is the only way to keep that order.
     *
     * @param  list<string>  $classes
     */
    private function imports(array $classes): string
    {
        $classes = array_values(array_unique($classes));
        sort($classes);

        return implode(PHP_EOL, array_map(
            static fn (string $class): string => "use {$class};",
            $classes,
        ));
    }

    /**
     * @param  array<string, array{0: string, 1: string}>  $pages
     * @return list<string>
     */
    private function pageClasses(string $panel, string $plural, array $pages): array
    {
        $classes = [];

        foreach ($pages as [$pageClass]) {
            $classes[] = "App\\Panels\\{$panel}\\Resources\\{$plural}\\Pages\\{$pageClass}";
        }

        return $classes;
    }

    /**
     * @param  array<string, array{0: string, 1: string}>  $pages
     */
    private function pageEntries(array $pages): string
    {
        $entries = [];

        foreach ($pages as $key => [$pageClass]) {
            $entries[] = "            '{$key}' => {$pageClass}::class,";
        }

        return implode(PHP_EOL, $entries);
    }

    /**
     * @param  array<string, array{0: string, 1: string}>  $pages
     * @return list<string>
     */
    private function actionClasses(array $pages): array
    {
        $classes = ['PandaPanel\\Actions\\DeleteAction', 'PandaPanel\\Actions\\DeleteBulkAction'];

        if (array_key_exists('view', $pages)) {
            $classes[] = 'PandaPanel\\Actions\\ViewAction';
        }

        if (array_key_exists('edit', $pages)) {
            $classes[] = 'PandaPanel\\Actions\\EditAction';
        }

        if ($this->option('soft-deletes')) {
            $classes[] = 'PandaPanel\\Actions\\ForceDeleteAction';
            $classes[] = 'PandaPanel\\Actions\\ForceDeleteBulkAction';
            $classes[] = 'PandaPanel\\Actions\\RestoreAction';
            $classes[] = 'PandaPanel\\Actions\\RestoreBulkAction';
            $classes[] = 'PandaPanel\\Tables\\Filters\\TrashedFilter';
        }

        return $classes;
    }

    /**
     * @param  array<string, array{0: string, 1: string}>  $pages
     */
    private function recordActions(string $class, array $pages): string
    {
        $actions = [];

        if (array_key_exists('view', $pages)) {
            $actions[] = "                ViewAction::make({$class}Resource::class),";
        }

        if (array_key_exists('edit', $pages)) {
            $actions[] = "                EditAction::make({$class}Resource::class),";
        }

        $actions[] = "                DeleteAction::make({$class}Resource::class),";

        if ($this->option('soft-deletes')) {
            $actions[] = "                RestoreAction::make({$class}Resource::class),";
            $actions[] = "                ForceDeleteAction::make({$class}Resource::class),";
        }

        return implode(PHP_EOL, $actions);
    }

    /**
     * The trashed filter is what puts a deleted record on screen. Generating
     * the restore actions without it would produce two buttons that can never
     * appear, which is how the flag used to behave.
     */
    private function filters(): string
    {
        return $this->option('soft-deletes')
            ? "                TrashedFilter::make('trashed'),"
            : '                //';
    }

    private function bulkActions(string $class): string
    {
        $actions = ["                DeleteBulkAction::make({$class}Resource::class),"];

        if ($this->option('soft-deletes')) {
            $actions[] = "                RestoreBulkAction::make({$class}Resource::class),";
            $actions[] = "                ForceDeleteBulkAction::make({$class}Resource::class),";
        }

        return implode(PHP_EOL, $actions);
    }

    /**
     * Declared on the resource, not inferred from the model: reaching a
     * trashed record, offering to restore it, and filtering for it only make
     * sense together, and this one flag turns on all three.
     */
    private function softDeletesDeclaration(): string
    {
        return $this->option('soft-deletes')
            ? "\n    protected static bool \$softDeletes = true;\n"
            : '';
    }

    private function resourcePath(string $panel, string $plural, string $file): string
    {
        return app_path("Panels/{$panel}/Resources/{$plural}/{$file}");
    }
}
