import {
    Check,
    CircleAlert,
    Copy,
    Download,
    Eye,
    Info,
    LayoutGrid,
    Link,
    Mail,
    Palette,
    Pencil,
    Plus,
    Receipt,
    RotateCcw,
    Search,
    Settings,
    Shield,
    Trash,
    Trash2,
    TriangleAlert,
    Unlink,
    Upload,
    User,
    Users,
} from '@lucide/vue';
import type { Component } from 'vue';

/**
 * Generated by `php artisan panel:icons`. Do not edit by hand.
 *
 * Icon names arrive from the server as plain strings. They resolve
 * through this map and nothing else: a name that is not a key here
 * renders no icon.
 *
 * This is deliberate. Resolving an arbitrary server-supplied name to a
 * component would let panel metadata reach into the bundle, and dynamic
 * imports keyed on a runtime string are not statically analysable
 * either. Lucide ships 1768 icons; only the ones a panel declares
 * belong in the bundle.
 */
const ICONS = {
    check: Check,
    'circle-alert': CircleAlert,
    copy: Copy,
    download: Download,
    eye: Eye,
    info: Info,
    'layout-grid': LayoutGrid,
    link: Link,
    mail: Mail,
    palette: Palette,
    pencil: Pencil,
    plus: Plus,
    receipt: Receipt,
    'rotate-ccw': RotateCcw,
    search: Search,
    settings: Settings,
    shield: Shield,
    trash: Trash,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    unlink: Unlink,
    upload: Upload,
    user: User,
    users: Users,
} satisfies Record<string, Component>;

export type PanelIconName = keyof typeof ICONS;

export function isPanelIconName(name: string): name is PanelIconName {
    return name in ICONS;
}

/**
 * Returns null for an unknown or absent name. Callers render no icon
 * rather than a broken one, and production stays console-clean.
 */
export function resolveIcon(name: string | null | undefined): Component | null {
    if (typeof name !== 'string' || !isPanelIconName(name)) {
        return null;
    }

    return ICONS[name];
}
