import {
    Check,
    CircleAlert,
    Copy,
    Download,
    Eye,
    Info,
    LayoutGrid,
    Link,
    Mail,
    Palette,
    Pencil,
    Plus,
    Receipt,
    RotateCcw,
    Search,
    Settings,
    Shield,
    Trash,
    Trash2,
    TriangleAlert,
    Unlink,
    Upload,
    User,
    Users,
} from '@lucide/vue';
import type { Component } from 'vue';

/**
 * Generated by `php artisan panel:icons`. Do not edit by hand.
 *
 * Icon names arrive from the server as plain strings. They resolve
 * through this map and nothing else: a name that is not a key here
 * renders no icon.
 *
 * This is deliberate. Resolving an arbitrary server-supplied name to a
 * component would let panel metadata reach into the bundle, and dynamic
 * imports keyed on a runtime string are not statically analysable
 * either. Lucide ships 1768 icons; only the ones a panel declares
 * belong in the bundle.
 */
const ICONS = {
    check: Check,
    'circle-alert': CircleAlert,
    copy: Copy,
    download: Download,
    eye: Eye,
    info: Info,
    'layout-grid': LayoutGrid,
    link: Link,
    mail: Mail,
    palette: Palette,
    pencil: Pencil,
    plus: Plus,
    receipt: Receipt,
    'rotate-ccw': RotateCcw,
    search: Search,
    settings: Settings,
    shield: Shield,
    trash: Trash,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    unlink: Unlink,
    upload: Upload,
    user: User,
    users: Users,
} satisfies Record<string, Component>;

export type PanelIconName = keyof typeof ICONS;

export function isPanelIconName(name: string): name is PanelIconName {
    return name in ICONS;
}

/** Names already complained about, so one typo is one warning. */
const missing = new Set<string>();

/**
 * Returns null for an unknown or absent name. Callers render no icon
 * rather than a broken one, and production stays console-clean.
 *
 * An unknown name used to be indistinguishable from no name at all:
 * both drew nothing, so a mistyped icon — or, far more often, one
 * declared in PHP after this file was last generated — was a missing
 * icon with no way to find out why. This registry is written by
 * `php artisan panel:icons`, and forgetting to re-run it is the whole
 * failure mode.
 *
 * Development only. In production the icon is still simply absent,
 * because a console message on a live panel helps nobody and this is
 * a build problem rather than a runtime one.
 */
export function resolveIcon(name: string | null | undefined): Component | null {
    if (typeof name !== 'string') {
        return null;
    }

    if (!isPanelIconName(name)) {
        if (import.meta.env.DEV && !missing.has(name)) {
            missing.add(name);

            console.warn(
                '[panel] The icon [' +
                    name +
                    '] is not in the icon registry, so nothing is drawn for it. ' +
                    'Run `php artisan panel:icons` to rebuild the registry from ' +
                    'the icons your panels declare.',
            );
        }

        return null;
    }

    return ICONS[name];
}
