<?php

declare(strict_types=1);

namespace PandaPanel\Cache;

use Illuminate\Support\Facades\File;
use PandaPanel\Core\Panel;
use PandaPanel\Core\PanelRegistry;
use PandaPanel\Discovery\PanelDiscoverer;

/**
 * The cached list of classes each panel owns.
 *
 * Only class names are stored, never resolved metadata. Authorization,
 * navigation active state, badge values, record data, and widget data all
 * depend on the current user or URL, so caching any of them would serve one
 * user's answers to another.
 *
 * When the manifest exists, discovery does not run at all: no filesystem
 * scan, no reflection, nothing per request. When it does not, discovery runs
 * once per panel during boot.
 */
final class PanelManifest
{
    /** @var array<string, array{resources: list<string>, pages: list<string>, widgets: list<string>}>|null */
    private ?array $panels = null;

    private bool $loaded = false;

    public function __construct(private readonly PanelDiscoverer $discoverer) {}

    /**
     * Beside the config, route and event caches.
     *
     * Through `bootstrapPath()` rather than `base_path('bootstrap/...')`,
     * because an application may move that directory — and a manifest written
     * somewhere `optimize:clear` does not look is a stale cache nobody can
     * clear.
     */
    public static function path(): string
    {
        return app()->bootstrapPath('cache/panels.php');
    }

    public function exists(): bool
    {
        return File::exists(self::path());
    }

    /**
     * The classes for one panel, from the manifest when it exists and from
     * discovery otherwise.
     *
     * @return array{resources: list<string>, pages: list<string>, widgets: list<string>}
     */
    public function for(Panel $panel): array
    {
        $cached = $this->load()[$panel->getId()] ?? null;

        if ($cached !== null) {
            return $cached;
        }

        return [
            'resources' => $this->discoverer->resources($panel),
            'pages' => $this->discoverer->pages($panel),
            'widgets' => $this->discoverer->widgets($panel),
        ];
    }

    /**
     * Builds the manifest for every registered panel and writes it
     * atomically, so a half-written file can never be loaded.
     *
     * @return array<string, array{resources: list<string>, pages: list<string>, widgets: list<string>}>
     */
    public function write(PanelRegistry $registry): array
    {
        $manifest = [];

        foreach ($registry->all() as $panel) {
            $manifest[$panel->getId()] = [
                'resources' => $this->merge($panel->getResources(), $this->discoverer->resources($panel)),
                'pages' => $this->merge($panel->getPages(), $this->discoverer->pages($panel)),
                'widgets' => $this->merge($panel->getWidgets(), $this->discoverer->widgets($panel)),
            ];
        }

        File::ensureDirectoryExists(dirname(self::path()));

        $temporary = self::path().'.'.getmypid().'.tmp';

        File::put($temporary, $this->render($manifest));
        File::move($temporary, self::path());

        $this->panels = $manifest;
        $this->loaded = true;

        return $manifest;
    }

    public function clear(): bool
    {
        $this->panels = null;
        $this->loaded = false;

        return $this->exists() ? File::delete(self::path()) : true;
    }

    /**
     * @return array<string, array{resources: list<string>, pages: list<string>, widgets: list<string>}>
     */
    private function load(): array
    {
        if ($this->loaded) {
            return $this->panels ?? [];
        }

        $this->loaded = true;

        if (! $this->exists()) {
            return $this->panels = [];
        }

        $manifest = require self::path();

        return $this->panels = is_array($manifest) ? $manifest : [];
    }

    /**
     * @param  list<string>  $explicit
     * @param  list<string>  $discovered
     * @return list<string>
     */
    private function merge(array $explicit, array $discovered): array
    {
        $merged = array_values(array_unique([...$explicit, ...$discovered]));
        sort($merged);

        return $merged;
    }

    /**
     * `var_export` rather than serialization, so the file is a plain
     * `return [...]` that opcache can hold and a human can read.
     *
     * @param  array<string, array<string, list<string>>>  $manifest
     */
    private function render(array $manifest): string
    {
        return '<?php'.PHP_EOL.PHP_EOL
            .'// Generated by "php artisan panel:cache". Do not edit.'.PHP_EOL.PHP_EOL
            .'return '.var_export($manifest, true).';'.PHP_EOL;
    }
}
